"""Multi-modal Hallucination Detection client (Hallo3D, Sec. 3.3 / Appendix A).

The training process sends one rendered view together with the 3D-aware
inquiry prompt P_I to a locally deployed LMM service (see
lmm_server/serve_lmm.py) and receives back the Enhanced Negative Prompt
P_E^- = D_psi(x, P_I) (Eq. 5), or None when the rendering lacks a complete
semantic structure (Eq. 8).
"""

import base64
import io
import json
import re
import urllib.request

import numpy as np

# Two-phase inquiry following the paper's multi-modal case study (Fig. 4):
# round 1 asks the LMM to inspect the rendering for spatial-structure
# inconsistencies; round 2 standardizes the output format with a one-shot
# reference so that P_E^- can be extracted with regular expressions.
INQUIRY_ROUND1 = (
    "This image was rendered from the 3D generated by AI with the text "
    "prompt '{prompt}', and you can look at the spatial structure of the "
    "object in the picture to see if there are any inconsistencies with "
    "body shape, perspective, surface texture, color, and so on. Describe "
    "the specific problems you observe in this image."
)

INQUIRY_ROUND2 = (
    "You are a master of graphic restoration. Based on your analysis above, "
    "summarize the 3D inconsistency problems as negative prompts for "
    "restoring the image I provided. Three references are as below:\n"
    "Negative Prompt: 'multi-head, unnatural lighting, smooth appearance, "
    "distorted color, long neck'\n"
    "Negative Prompt: 'ghost image, incongruous perspective, obscured body "
    "positioning, indistinct fingers'\n"
    "Negative Prompt: 'blurry background, duplicated feature, unsharp "
    "edges, lack of detail clarity'\n"
    "Answer with ONE line in the same format. Use your own short phrases "
    "naming the problems from your analysis above (do not copy the "
    "references); if no major problem was found, name the minor "
    "imperfections that could still be improved. Only if the image shows "
    "no recognizable object at all (pure noise or fragments), reply with "
    "exactly: None"
)

_NEG_PROMPT_RE = re.compile(
    r"negative\s*prompt[\"'`]?\s*[:：]\s*[\"'`]?([^\"'`\n]+)", re.IGNORECASE
)


def extract_negative_prompt(text: str):
    """Regex extraction of P_E^- from the LMM response; None if absent."""
    if text is None:
        return None
    stripped = text.strip()
    if stripped.lower() in ("none", "none.", "'none'", '"none"'):
        return None
    match = _NEG_PROMPT_RE.search(stripped)
    if match is None:
        return None
    result = match.group(1).strip().strip("'\"` .")
    # guard against the model answering "None" inside the template format
    if not result or result.lower() == "none":
        return None
    return result


def image_tensor_to_b64png(img_chw) -> str:
    """[3,H,W] float tensor in [0,1] -> base64 PNG string."""
    from PIL import Image

    arr = (
        (img_chw.detach().float().clamp(0, 1) * 255)
        .permute(1, 2, 0)
        .cpu()
        .numpy()
        .astype(np.uint8)
    )
    buf = io.BytesIO()
    Image.fromarray(arr).save(buf, format="PNG")
    return base64.b64encode(buf.getvalue()).decode("ascii")


class LMMDetectorClient:
    def __init__(self, server_url: str, timeout: float = 60.0):
        self.server_url = server_url.rstrip("/")
        self.timeout = timeout
        self._warned = False

    def _post(self, payload: dict):
        req = urllib.request.Request(
            self.server_url + "/query",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=self.timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))["response"]

    def query(self, image_chw, scene_prompt: str):
        """Two-round inquiry (Fig. 4); returns P_E^- (str) or None."""
        image_b64 = image_tensor_to_b64png(image_chw)
        round1 = INQUIRY_ROUND1.format(prompt=scene_prompt)
        try:
            analysis = self._post({"image_b64": image_b64, "prompt": round1})
            summary = self._post(
                {
                    "image_b64": image_b64,
                    "prompt": INQUIRY_ROUND2,
                    "history": [[round1, analysis]],
                }
            )
        except Exception as e:  # service down -> degrade to SDS-only (Eq. 8)
            if not self._warned:
                msg = (
                    f"[Hallo3D] LMM detector unreachable at {self.server_url} "
                    f"({e}); falling back to L_SDS only."
                )
                try:
                    import threestudio

                    threestudio.warn(msg)
                except ImportError:
                    print(msg)
                self._warned = True
            return None
        return extract_negative_prompt(summary)
